apiVersion: v1
kind: Service
metadata:
  name: bind9
spec:
  selector:
    app: bind9
  type: LoadBalancer
  loadBalancerIP: 10.0.253.253
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: udp
    - protocol: TCP
      port: 53
      targetPort: 53
      name: tcp
