services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: dns-prod-1
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - BIND9_USER=root
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config/:/etc/bind/:rw
