apiVersion: v1
kind: Service
metadata:
  name: omada-controller
  labels:
    app.kubernetes.io/instance: omada-controller
    app.kubernetes.io/name: omada-controller
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.60.12
  ports:
  - port: 8043
    targetPort: 8043
    protocol: TCP
    name: https
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  - port: 8843
    targetPort: 8843
    protocol: TCP
    name: unknown
  - port: 27001
    targetPort: 27001
    protocol: UDP
    name: app-discovery
  - port: 29810
    targetPort: 29810
    protocol: UDP
    name: port-discovery
  - port: 29811
    targetPort: 29811
    protocol: TCP
    name: manager-v1
  - port: 29812
    targetPort: 29812
    protocol: TCP
    name: adopt-v1
  - port: 29813
    targetPort: 29813
    protocol: TCP
    name: upgrade
  - port: 29814
    targetPort: 29814
    protocol: TCP
    name: manager-v2
  - port: 29815
    targetPort: 29815
    protocol: TCP
    name: transfer
  - port: 29816
    targetPort: 29816
    protocol: TCP
    name: rtty
  selector:
    app.kubernetes.io/instance: omada-controller
    app.kubernetes.io/name: omada-controller
